insert into municipios(codmunicipio ,nomemunicipio, codestado) values(1, 'RIO BRANCO', 1);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(2, 'BOM JESUS DA LAPA', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(3, 'JUAZEIRO DO NORTE', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(4, 'APARECIDA DE GOIÂNIA', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(5, 'BONFINÓPOLIS DE MINAS', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(6, 'CONTAGEM', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(7, 'PEÇANHA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(8, 'SABARÁ', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(9, 'PONTA GROSSA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(10, 'SANTANA DO PARAÍSO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(11, 'TERESINA', 7);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(12, 'ANAHY', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(13, 'APUCARANA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(14, 'ARAUCÁRIA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(15, 'BOA VISTA DA APARECIDA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(16, 'CAFELÂNDIA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(17, 'CAMPINA GRANDE DO SUL', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(18, 'CARAMBEÍ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(19, 'CLEVELÂNDIA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(20, 'CORONEL VIVIDA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(21, 'CURITIBA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(22, 'ESPIGÃO ALTO DO IGUAÇU', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(23, 'FERNANDES PINHEIRO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(24, 'FOZ DO IGUAÇU', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(25, 'GUAÍRA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(26, 'GUARAPUAVA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(27, 'IBEMA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(28, 'IGUATU', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(29, 'ITAPEJARA D OESTE', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(30, 'LONDRINA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(31, 'MARECHAL CÂNDIDO RONDON', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(32, 'NOVA LARANJEIRAS', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(33, 'PORTO BARREIRO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(34, 'RIO NEGRO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(35, 'SANTA TEREZA DO OESTE', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(36, 'SANTO ANTÔNIO DO SUDOESTE', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(37, 'SÃO JOSÉ DOS PINHAIS', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(38, 'SAUDADE DO IGUAÇU', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(39, 'TOLEDO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(40, 'TRÊS BARRAS DO PARANÁ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(41, 'UNIÃO DA VITÓRIA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(42, 'NITERÓI', 8);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(43, 'ALMIRANTE TAMANDARÉ DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(44, 'BARÃO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(45, 'BARRACÃO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(46, 'CANGUÇU', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(47, 'DONA FRANCISCA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(48, 'FAXINAL DO SOTURNO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(49, 'FONTOURA XAVIER', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(50, 'JAGUARI', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(51, 'JÚLIO DE CASTILHOS', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(52, 'NOVA PALMA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(53, 'PANTANO GRANDE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(54, 'PEDRO OSÓRIO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(55, 'PELOTAS', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(56, 'RIO PARDO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(57, 'RONDINHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(58, 'ROSÁRIO DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(59, 'SANTA CRUZ DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(60, 'SANTA MARIA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(61, 'SÃO JOSÉ DO NORTE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(62, 'SÃO PEDRO DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(63, 'SINIMBU', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(64, 'SOBRADINHO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(65, 'VALE DO SOL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(66, 'VERA CRUZ', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(67, 'WESTFÁLIA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(68, 'ABDON BATISTA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(69, 'AGRONÔMICA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(70, 'BLUMENAU', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(71, 'BOMBINHAS', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(72, 'CAPINZAL', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(73, 'DIONÍSIO CERQUEIRA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(74, 'FLORIANÓPOLIS', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(75, 'GRAVATAL', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(76, 'GUARAMIRIM', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(77, 'IPUMIRIM', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(78, 'LAURENTINO', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(79, 'LEBON RÉGIS', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(80, 'LUIZ ALVES', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(81, 'NOVA ERECHIM', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(82, 'OURO', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(83, 'SANTO AMARO DA IMPERATRIZ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(84, 'SÃO DOMINGOS', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(85, 'SÃO LOURENÇO DO OESTE', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(86, 'SEARA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(87, 'XANXERÊ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(88, 'ANGATUBA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(89, 'ARAÇOIABA DA SERRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(90, 'ATIBAIA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(91, 'BEBEDOURO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(92, 'CONCHAS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(93, 'INDAIATUBA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(94, 'ITAPETININGA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(95, 'ITAPEVA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(96, 'JUNDIAÍ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(97, 'MOGI DAS CRUZES', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(98, 'MONTE ALTO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(99, 'PACAEMBU', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(100, 'PIRACICABA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(101, 'PRESIDENTE PRUDENTE', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(102, 'SANTA BÁRBARA D OESTE', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(103, 'SÃO PEDRO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(104, 'TAMBAÚ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(105, 'TIETÊ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(106, 'VOTORANTIM', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(107, 'GURUPI', 12);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(108, 'UBERABA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(109, 'SAPIRANGA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(110, 'SANTARÉM', 13);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(111, 'CERRO LARGO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(112, 'IRARÁ', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(113, 'DOIS VIZINHOS', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(114, 'PERUÍBE', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(115, 'BAIXO GUANDU', 14);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(116, 'SANTO ANTÔNIO DA PLATINA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(117, 'RIO GRANDE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(118, 'RIBEIRÃO PIRES', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(119, 'PALMAS', 12);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(120, 'SÃO JOSÉ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(121, 'RIO CLARO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(122, 'ITAPEVI', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(123, 'BIRIGUI', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(124, 'JARAGUÁ DO SUL', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(125, 'ITURAMA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(126, 'MONTENEGRO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(127, 'VÁRZEA PAULISTA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(128, 'GARUVA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(129, 'CERES', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(130, 'MARAU', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(131, 'VITÓRIA DA CONQUISTA', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(132, 'PORTO XAVIER', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(133, 'SANTA VITÓRIA DO PALMAR', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(134, 'OLINDINA', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(135, 'CAPIVARI', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(136, 'MONTE MOR', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(137, 'CAÇAPAVA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(138, 'NOVA ESPERANÇA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(139, 'BARBALHA', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(140, 'NAVEGANTES', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(141, 'TRÊS CORAÇÕES', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(142, 'JAGUARARI', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(143, 'ACOPIARA', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(144, 'CASIMIRO DE ABREU', 8);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(145, 'SANTO ÂNGELO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(146, 'PORTO MURTINHO', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(147, 'SÃO MIGUEL DO OESTE', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(148, 'TAPERA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(149, 'FARROUPILHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(150, 'MARTINHO CAMPOS', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(151, 'MAFRA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(152, 'SERTÃOZINHO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(153, 'SÃO SEBASTIÃO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(154, 'JI-PARANÁ', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(155, 'SARANDI', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(156, 'PALMEIRA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(157, 'CRUZ ALTA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(158, 'DIVINÓPOLIS', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(159, 'IÇARA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(160, 'CASTRO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(161, 'PARANAVAÍ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(162, 'VENÂNCIO AIRES', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(163, 'TELÊMACO BORBA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(164, 'PORTO VELHO', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(165, 'GOIÂNIA', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(166, 'JOAQUIM TÁVORA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(167, 'SANTO ESTÊVÃO', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(168, 'ANÁPOLIS', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(169, 'GUARANTÃ DO NORTE', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(170, 'IPIRANGA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(171, 'CANDELÁRIA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(172, 'ARACAJU', 18);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(173, 'VARGEM GRANDE DO SUL', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(174, 'NOVA CANAÃ DO NORTE', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(175, 'TAQUARANA', 19);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(176, 'CANELA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(177, 'GUARATINGUETÁ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(178, 'IBIÁ', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(179, 'BURITIS', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(180, 'ESPERA FELIZ', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(181, 'GUARULHOS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(182, 'BALNEÁRIO PINHAL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(183, 'ABELARDO LUZ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(184, 'ARROIO GRANDE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(185, 'SÃO LUÍS', 20);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(186, 'CACOAL', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(187, 'ARTUR NOGUEIRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(188, 'GUARANIAÇU', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(189, 'CAMPOS NOVOS', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(190, 'VARGEM GRANDE PAULISTA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(191, 'ARAÇATUBA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(192, 'ITANHAÉM', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(193, 'MOSSORÓ', 21);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(194, 'CAUCAIA', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(195, 'HORIZONTE', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(196, 'CARIACICA', 14);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(197, 'SÃO JOÃO EVANGELISTA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(198, 'VILA VELHA', 14);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(199, 'UBERLÂNDIA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(200, 'BOM JESUS DE GOIÁS', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(201, 'PASSO FUNDO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(202, 'VINHEDO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(203, 'RONDONÓPOLIS', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(204, 'ITATIBA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(205, 'MIRANDA', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(206, 'BAGÉ', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(207, 'BOA ESPERANÇA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(208, 'PALHOÇA', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(209, 'ARAGUAÍNA', 12);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(210, 'MANAUS', 22);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(211, 'BARRA', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(212, 'IBOTIRAMA', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(213, 'SALVADOR', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(214, 'MAURITI', 3);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(215, 'CACHOEIRO DE ITAPEMIRIM', 14);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(216, 'ALEXÂNIA', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(217, 'JATAÍ', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(218, 'LUZIÂNIA', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(219, 'MINEIROS', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(220, 'RIO VERDE', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(221, 'SENADOR CANEDO', 4);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(222, 'BETIM', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(223, 'BRASÍLIA DE MINAS', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(224, 'BRUMADINHO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(225, 'BURITIZEIRO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(226, 'CAETÉ', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(227, 'CAPIM BRANCO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(228, 'CARMO DO PARANAÍBA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(229, 'ITUIUTABA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(230, 'OURO FINO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(231, 'PATROCÍNIO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(232, 'POMPÉU', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(233, 'POUSO ALEGRE', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(234, 'SÃO JOSÉ DA LAPA', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(235, 'VESPASIANO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(236, 'AQUIDAUANA', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(237, 'COXIM', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(238, 'DOURADOS', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(239, 'MARACAJU', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(240, 'NAVIRAÍ', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(241, 'NOVA ANDRADINA', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(242, 'RIO BRILHANTE', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(243, 'BARRA DO GARÇAS', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(244, 'CAMPO NOVO DO PARECIS', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(245, 'CUIABÁ', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(246, 'NOVA MUTUM', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(247, 'DOM ELISEU', 13);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(248, 'JOÃO PESSOA', 23);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(249, 'PATOS', 23);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(250, 'RECIFE', 24);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(251, 'FAZENDA RIO GRANDE', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(252, 'GOIOERÊ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(253, 'IRATI', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(254, 'JAGUARIAÍVA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(255, 'LAPA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(256, 'LARANJEIRAS DO SUL', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(257, 'MARIALVA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(258, 'MARINGÁ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(259, 'PALMEIRA- PALOTINA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(260, 'PALOTINA- PARANAVAÍ', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(261, 'PARANAVAÍ- PATO BRANCO', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(262, 'PATO BRANCO- PITANGA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(263, 'QUATRO BARRAS', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(264, 'ROLÂNDIA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(265, 'UMUARAMA', 6);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(266, 'SÃO GONÇALO', 8);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(267, 'MACHADINHO D OESTE', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(268, 'ALEGRETE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(269, 'CACHOEIRA DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(270, 'CAMAQUÃ', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(271, 'CAMPO BOM', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(272, 'CAPELA DE SANTANA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(273, 'CARAZINHO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(274, 'CARLOS BARBOSA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(275, 'CAXIAS DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(276, 'CHARQUEADAS', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(277, 'ESTRELA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(278, 'FLORES DA CUNHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(279, 'FREDERICO WESTPHALEN', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(280, 'GARIBALDI', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(281, 'GRAMADO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(282, 'IGREJINHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(283, 'IJUÍ', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(284, 'LAJEADO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(285, 'NOVA HARTZ', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(286, 'NOVO HAMBURGO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(287, 'PALMEIRA DAS MISSÕES', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(288, 'PORTO ALEGRE', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(289, 'SÃO BORJA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(290, 'SÃO LOURENÇO DO SUL', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(291, 'TAQUARI', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(292, 'TEUTÔNIA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(293, 'TORRES', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(294, 'VACARIA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(295, 'BIGUAÇU', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(296, 'CAMBORIÚ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(297, 'FRAIBURGO', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(298, 'GASPAR', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(299, 'INDAIAL', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(300, 'ITAJAÍ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(301, 'PORTO UNIÃO', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(302, 'RIO DO SUL', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(303, 'TIMBÓ', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(304, 'XAXIM', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(305, 'NOSSA SENHORA DO SOCORRO', 18);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(306, 'AGUDOS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(307, 'ANDRADINA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(308, 'BAURU', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(309, 'CABREÚVA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(310, 'CAMPINAS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(311, 'CATANDUVA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(312, 'GARÇA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(313, 'GUARUJÁ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(314, 'ITAPECERICA DA SERRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(315, 'JACAREÍ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(316, 'LARANJAL PAULISTA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(317, 'LIMEIRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(318, 'LINS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(319, 'MATÃO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(320, 'PITANGUEIRAS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(321, 'PORTO FELIZ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(322, 'PORTO FERREIRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(323, 'RIBEIRÃO PRETO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(324, 'SANTA CRUZ DO RIO PARDO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(325, 'SÃO JOSÉ DO RIO PRETO', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(326, 'SÃO JOSÉ DOS CAMPOS', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(327, 'SÃO MANUEL', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(328, 'SERRA NEGRA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(329, 'SOROCABA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(330, 'TAUBATÉ', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(331, 'PARAÍSO DO TOCANTINS', 12);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(332, 'CAMAÇARI', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(333, 'SÃO DESIDÉRIO', 2);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(334, 'BRASÍLIA', 25);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(335, 'CLÁUDIO', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(336, 'SETE LAGOAS', 5);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(337, 'CAMPO GRANDE', 15);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(338, 'SINOP', 17);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(339, 'JURUTI', 13);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(340, 'MARABÁ', 13);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(341, 'CARUARU- PETROLINA', 24);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(342, 'RESENDE', 8);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(343, 'RIO DE JANEIRO', 8);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(344, 'ARIQUEMES', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(345, 'VILHENA', 16);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(346, 'BENTO GONÇALVES', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(347, 'CACHOEIRINHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(348, 'JAGUARÃO', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(349, 'LAGOA VERMELHA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(350, 'SANTA ROSA', 9);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(351, 'BRUSQUE', 10);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(352, 'BERTIOGA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(353, 'HORTOLÂNDIA', 11);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(354, 'COLINAS DO TOCANTINS', 12);
insert into municipios(codmunicipio ,nomemunicipio, codestado) values(355, 'PORTO NACIONAL', 12);
